### ISSUE TITLE
Robot Kit : Servo 0

### ISSUE THREAD

**Issue by driesderoeck** [Fri3dCamp/Fri3dBadge#12]
Issue related to the robot kit (crossposted at the bottom of http://wiki2018.fri3d.be/index.php?title=Robot_kit)

After building and calibrating, the left ankle servo (attached to servo connector #0) behaves differently compared to the other servo's. While all servo's feel 'powered' (ie. they can't be moved once powered on) the left ankle servo remains free. In most of the movements I have the impression the servo is not moving (although it does move and calibrate when the servo's are being 'attached'). I tried swapping servo's, but it doesn't seem to be related to the servo itself.
Any pointers to where I should be looking to fix this?

**Comment by Brubacker** [comment]
Same issue here, when move the servo around to another pin (in the .h file, swapped it with one of the hips) it does exactly what is needed, and that hip is now no longer powered. It seems that there is something wrong with the code for setting the signal on that specific pin.

**Comment by calmera** [comment]
Ok, the problem actually is a conflict between the Buzzer timer channel and the timer channel used by the first servo. Fixed as of now :).

Make sure to re-install the fri3d library in the arduino ide if you want to use it.
