### ISSUE TITLE
error als je buttonslibrary en ble beacon tegelijk wil gebruiken

### ISSUE THREAD

**Issue by kurtbeheydt** [Fri3dCamp/Fri3dBadge#4]
Op basis van de default firmware de button library gebruikt:

```
buttons.setReleasedCallback(0, startFightMode); // button 0 starts fightmode
buttons.setReleasedCallback(1, startConquerMode); // button 1 starts fightmode
buttons.startDebounceThread();
```

Tijden de uitvoering crasht ``startConquerMode`` 

```
CORRUPT HEAP: multi_heap.c:233 detected at 0x3ffe4660
abort() was called at PC 0x4008cca6 on core 0

Backtrace: 0x4008d5f0:0x3ffe49e0 0x4008d7cb:0x3ffe4a00 0x4008cca6:0x3ffe4a20 0x4008cf5c:0x3ffe4a40 0x4008d322:0x3ffe4a60 0x40084056:0x3ffe4a80 0x40088ced:0x3ffe4aa0 0x4000bec7:0x3ffe4ac0 0x4016a2d1:0x3ffe4ae0 0x4017cf2e:0x3ffe4b00 0x400d2e9a:0x3ffe4b20 0x400d302b:0x3ffe4be0 0x400d6bb5:0x3ffe4c10 0x400d6bcc:0x3ffe4c30

Rebooting...
```

Beetje debug via serial.print leert dat het tussen 00 en 01 gebeurt:

```
BLEBeacon oBeacon = BLEBeacon();
Serial.println("00");
oBeacon.setManufacturerId(0x4C00); // fake Apple 0x004C LSB (ENDIAN_CHANGE_U16!)
oBeacon.setProximityUUID(BLEUUID(BEACON_UUID));
oBeacon.setMajor((state & 0xFFFF0000) >> 16);
oBeacon.setMinor(state & 0xFFFF);
Serial.println("01");
```

Met mijn eigen buttonstate functies werkt het wel, maar mijn arduino kennis is niet gevorderd genoeg om die multi_heap error te debuggen.

**Comment by aliekens** [comment]
Ik denk dat je inderdaad best terugvalt op je eigen buttonstate routines. De button debouncer loopt op aparte core met beperkte heap, dus als je callback te groot is dan zou die heap size wel eens kunnen overlopen. Een callback die een of andere state verzet, dat moet wel kunnen, maar diepgaande code beginnen runnen in die callback is idd tricky.

**Comment by kurtbeheydt** [comment]
ok, ik gebruik men eigen routines dan ;)
